version: "2.1"

services:
  # https://hub.docker.com/r/homeassistant/home-assistant
  homeassistant:
    image: homeassistant/home-assistant:2023.11.3@sha256:feffc0b8227dbbf9d1bf61c465ff54b24aff2c990a1e54ea7219c4b300260ef9
    network_mode: host
    volumes:
      - config:/config
    labels:
      io.balena.features.dbus: "1"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    privileged: true

  # https://hub.docker.com/_/eclipse-mosquitto
  mqtt:
    build: mqtt
    ports:
      - 1883:1883
    volumes:
      - mqtt:/mosquitto/data
    tmpfs:
      - /mosquitto/log

  # https://esphome.io/guides/getting_started_command_line.html#installation
  esphome:
    image: ghcr.io/esphome/esphome:2023.11.6@sha256:783e2131fcff2c457846339a80f6ed981e58e5f86de3578f742e3bed87f7d5b2
    volumes:
      - esphome:/config
    privileged: true
    network_mode: host

  # https://www.zigbee2mqtt.io/guide/getting-started/#installation
  zigbee2mqtt:
    build: zigbee2mqtt
    restart: no
    volumes:
      - zigbee2mqtt:/app/data
    ports:
      - 7000:7000
    privileged: true

  # https://hub.docker.com/r/codercom/code-server
  code-server:
    image: codercom/code-server:4.19.1@sha256:993c381c28a3738b903ac21180f5f9dab8f2aa547bbb0b9d69bea558691e10d3
    command:
      - --port=9000
      - --auth=none
      - --extensions-dir=/config/.vscode
      - --user-data-dir=/config/.vscode
      - /config
    working_dir: /config
    ports:
      - 9000:9000/tcp
    volumes:
      - config:/config
    user: root

  # https://hub.docker.com/_/influxdb
  influxdb:
    image: influxdb:1.8.10@sha256:fa0bd1644943ffe40549c0dc45c2a6217618b5cb53abf610aea38d60cf6bea1f
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  # https://hub.docker.com/r/grafana/grafana
  grafana:
    image: grafana/grafana:10.2.2@sha256:e3e9c2b5776fe3657f4954dfa91579224f98a0316f51d431989b15425e95530f
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: homeassistant

  duplicati:
    image: linuxserver/duplicati:v2.0.6.3-2.0.6.3_beta_2021-06-17-ls154@sha256:bcd89eb054ff1bce2c438d5eaab39120ab71580d44317c41a65a8e1fd91fbda5
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - "8200:8200/tcp"
    tmpfs:
      - /tmp
    volumes:
      - duplicati:/config
      - config:/volumes/config
      - influxdb:/volumes/influxdb
      - grafana:/volumes/grafana
      - zigbee2mqtt:/volumes/zigbee2mqtt
      - frigate-media:/volumes/frigate-media
      - tailscale:/volumes/tailscale
      - netdatalib:/volumes/netdatalib
      - esphome:/volumes/esphome

  # https://blakeblackshear.github.io/frigate/installation
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.12.1@sha256:bb7f7e76a13eccef0b12704e5851cc774a12af1f12df387d6a70a796a3e938c3
    privileged: true
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    volumes:
      - config:/config
      - frigate-media:/media/frigate
    tmpfs:
      - /tmp/cache
    shm_size: 2048M
    environment:
      FRIGATE_RTSP_PASSWORD: "balena"
      CONFIG_FILE: "/config/frigate.yml"
    labels:
      io.balena.features.kernel-modules: 1
    devices:
      - /dev/dri:/dev/dri

  # https://hub.docker.com/r/mrlt8/wyze-bridge/tags
  wyze-bridge:
    image: mrlt8/wyze-bridge:2.5.2@sha256:fbc96561e606a4233a49296e32fddb5355510075d975583d92d31fea5b62d706
    ports:
      # - 1935:1935 # RTMP
      # - 8554:8554 # RTSP
      # - 8888:8888 # HLS
      # - 8889:8889 # WebRTC
      # - 8189:8189/udp # WebRTC/ICE
      - 5001:5000 # WEB-UI
    volumes:
      - wyze-tokens:/tokens

  # https://github.com/klutchell/balena-tailscale
  tailscale:
    build: tailscale
    network_mode: host
    restart: on-failure
    volumes:
      - tailscale:/var/lib/tailscale
    labels:
      - io.balena.features.kernel-modules=1
    cap_add:
      - net_admin
      - net_raw
      - sys_module
    tmpfs:
      - /tmp
      - /var/run/
    environment:
      TS_EXTRA_ARGS: --reset
      REQUIRE_AUTH_KEY: "true"

  netdata:
    image: netdata/netdata:v1.43.2@sha256:0116a5a4dbfedd84d80eba320f5d99d547da5d9bc0841adde0d7f13bed25f73a
    privileged: true
    network_mode: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.sysfs: 1
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "991" # ls -nd /var/run/balena.sock | awk '{print $4}'

volumes:
  config: {}
  influxdb: {}
  grafana: {}
  mqtt: {}
  zigbee2mqtt: {}
  duplicati: {}
  frigate-media: {}
  wyze-tokens: {}
  tailscale: {}
  netdatalib: {}
  netdatacache: {}
  esphome: {}
