version: "2.1"

services:
  # https://hub.docker.com/r/homeassistant/home-assistant
  homeassistant:
    image: homeassistant/home-assistant:2024.5.3@sha256:cd3e0dc0df5b2013ae589e9f0044e1093c28c31dc653f36db3df10ba8e898dd6
    network_mode: host
    volumes:
      - config:/config
    labels:
      io.balena.features.dbus: "1"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    privileged: true

  # https://hub.docker.com/_/eclipse-mosquitto
  mqtt:
    build: mqtt
    ports:
      - 1883:1883
    volumes:
      - mqtt:/mosquitto/data
    tmpfs:
      - /mosquitto/log

  # https://esphome.io/guides/getting_started_command_line.html#installation
  esphome:
    image: ghcr.io/esphome/esphome:2024.4.2@sha256:4071afac339cc2e35a9e9d533934463418d970fb4566699512c544ae87fa38d5
    volumes:
      - esphome:/config
    privileged: true
    network_mode: host

  # https://www.zigbee2mqtt.io/guide/getting-started/#installation
  zigbee2mqtt:
    build: zigbee2mqtt
    volumes:
      - zigbee2mqtt:/app/data
    ports:
      - 7000:7000
    privileged: true

  # https://hub.docker.com/r/codercom/code-server
  code-server:
    image: codercom/code-server:4.89.0@sha256:19d4480011242bcad63e84dd2408ccbf834ce48a9d34381dcc22bf126daf6873
    command:
      - --port=9000
      - --auth=none
      - --extensions-dir=/config/.vscode
      - --user-data-dir=/config/.vscode
      - /config
    working_dir: /config
    ports:
      - 9000:9000/tcp
    volumes:
      - config:/config
      - zigbee2mqtt:/config/zigbee2mqtt
      - esphome:/config/esphome
      - frigate-config:/config/frigate
    user: root

  # https://hub.docker.com/_/influxdb
  influxdb:
    image: influxdb:1.8.10@sha256:675da300cf089bdc1f1c2e042b14454099c90a87fd58a42798b5fbfde8c529cb
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  # https://hub.docker.com/r/grafana/grafana
  grafana:
    image: grafana/grafana:10.4.2@sha256:7d5faae481a4c6f436c99e98af11534f7fd5e8d3e35213552dd1dd02bc393d2e
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: homeassistant

  duplicati:
    image: linuxserver/duplicati:v2.0.6.3-2.0.6.3_beta_2021-06-17-ls154@sha256:bcd89eb054ff1bce2c438d5eaab39120ab71580d44317c41a65a8e1fd91fbda5
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - "8200:8200/tcp"
    tmpfs:
      - /tmp
    volumes:
      - duplicati:/config
      - config:/volumes/config
      - influxdb:/volumes/influxdb
      - grafana:/volumes/grafana
      - zigbee2mqtt:/volumes/zigbee2mqtt
      - frigate-media:/volumes/frigate-media
      - tailscale:/volumes/tailscale
      - netdatalib:/volumes/netdatalib
      - esphome:/volumes/esphome

  # https://docs.frigate.video/frigate/installation
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.13.2@sha256:2906991ccad85035b176941f9dedfd35088ff710c39d45ef1baa9a49f2b16734
    privileged: true
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    volumes:
      - frigate-config:/config
      - frigate-media:/media/frigate
    tmpfs:
      - /tmp/cache
    shm_size: 2048M
    environment:
      FRIGATE_RTSP_PASSWORD: "balena"
      CONFIG_FILE: "/config/config.yml"
    labels:
      io.balena.features.kernel-modules: 1
    devices:
      - /dev/dri:/dev/dri

  # https://hub.docker.com/r/mrlt8/wyze-bridge/tags
  wyze-bridge:
    image: mrlt8/wyze-bridge:2.9.1@sha256:1230c02fca68839f1dce0f3352c432128a9b9f887bb23d8ca2d89e197e062801
    ports:
      # - 1935:1935 # RTMP
      # - 8554:8554 # RTSP
      # - 8888:8888 # HLS
      # - 8889:8889 # WebRTC
      # - 8189:8189/udp # WebRTC/ICE
      - 5001:5000 # WEB-UI
    volumes:
      - wyze-tokens:/tokens

  # https://hub.docker.com/r/tailscale/tailscale
  # https://github.com/tailscale/tailscale/blob/main/cmd/containerboot/main.go
  # https://tailscale.com/kb/1282/docker
  # https://tailscale.com/kb/1278/tailscaled
  # https://tailscale.com/kb/1241/tailscale-up
  # https://tailscale.com/kb/1242/tailscale-serve
  # https://tailscale.com/kb/1311/tailscale-funnel
  tailscale:
    image: tailscale/tailscale:v1.64.2@sha256:7ee2ab4b9efadc5a68c92fb4549206eedac240a758f61b5431e39e8c0806930d
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_SOCKET: /var/run/tailscale/tailscaled.sock
      TS_USERSPACE: false
      TS_AUTH_ONCE: false
      TS_HOSTNAME: homeassistant
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    tmpfs:
      - /tmp
      - /run
    volumes:
      - tailscale:/var/lib/tailscale
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        modprobe tun || true
        modprobe wireguard || true
        mkdir -p /dev/net
        [ ! -c /dev/net/tun ] && mknod /dev/net/tun c 10 200
        /usr/local/bin/containerboot

  netdata:
    image: netdata/netdata:v1.45.4@sha256:f4ee90aac06d641ddb999d0e6d1e78c8f2b1d18367b2db42af195d47ccbf3a32
    privileged: true
    network_mode: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.sysfs: 1
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "991" # ls -nd /var/run/balena.sock | awk '{print $4}'

volumes:
  config: {}
  influxdb: {}
  grafana: {}
  mqtt: {}
  zigbee2mqtt: {}
  duplicati: {}
  frigate-config: {}
  frigate-media: {}
  wyze-tokens: {}
  tailscale: {}
  netdatalib: {}
  netdatacache: {}
  esphome: {}
