version: "2.1"

services:
  # https://hub.docker.com/r/homeassistant/home-assistant
  homeassistant:
    image: homeassistant/home-assistant:2024.7.3@sha256:f8f13f6da9b38f6e33b9c40fded2a84ccd13ad69eb2a7e53bb045778fbccc229
    network_mode: host
    volumes:
      - config:/config
    labels:
      io.balena.features.dbus: "1"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    privileged: true

  # https://hub.docker.com/_/eclipse-mosquitto
  mqtt:
    build: mqtt
    ports:
      - 1883:1883
    volumes:
      - mqtt:/mosquitto/data
    tmpfs:
      - /mosquitto/log

  # https://esphome.io/guides/getting_started_command_line.html#installation
  esphome:
    image: ghcr.io/esphome/esphome:2024.7.1@sha256:e7ab6a50806dfe787192077914986469edb24215290f4a0f5df86253281ae6a8
    volumes:
      - esphome:/config
    privileged: true
    network_mode: host

  # https://www.zigbee2mqtt.io/guide/getting-started/#installation
  zigbee2mqtt:
    build: zigbee2mqtt
    volumes:
      - zigbee2mqtt:/app/data
    ports:
      - 7000:7000
    privileged: true

  # https://hub.docker.com/r/codercom/code-server
  code-server:
    image: codercom/code-server:4.91.1@sha256:8403442d3472e411f72b6a5267b5ee0e62db27e258d81efebef40c3b41219970
    command:
      - --port=9000
      - --auth=none
      - --extensions-dir=/config/.vscode
      - --user-data-dir=/config/.vscode
      - /config
    working_dir: /config
    ports:
      - 9000:9000/tcp
    volumes:
      - config:/config
      - zigbee2mqtt:/config/zigbee2mqtt
      - esphome:/config/esphome
      - frigate-config:/config/frigate
    user: root

  # https://hub.docker.com/_/influxdb
  influxdb:
    image: influxdb:1.8.10@sha256:098f81c86aa2f8cd3dda5fbf80f0a1be36dd4627d8b6f4c69d2adcc4081bae57
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  # https://hub.docker.com/r/grafana/grafana
  grafana:
    image: grafana/grafana:11.1.0@sha256:079600c9517b678c10cda6006b4487d3174512fd4c6cface37df7822756ed7a5
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: homeassistant

  # https://fleet.linuxserver.io/image?name=linuxserver/duplicati
  # https://docs.linuxserver.io/images/docker-duplicati/
  # https://hub.docker.com/r/linuxserver/duplicati
  duplicati:
    image: lscr.io/linuxserver/duplicati:2.0.8@sha256:2cd598c5faa34476fb1fdbd9c652ddc67c8729f5f7cc9b11426d58c5e69d0c18
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - "8200:8200/tcp"
    tmpfs:
      - /tmp
    volumes:
      - duplicati:/config
      - config:/volumes/config
      - influxdb:/volumes/influxdb
      - grafana:/volumes/grafana
      - zigbee2mqtt:/volumes/zigbee2mqtt
      - frigate-media:/volumes/frigate-media
      - tailscale:/volumes/tailscale
      - netdatalib:/volumes/netdatalib
      - esphome:/volumes/esphome

  # https://docs.frigate.video/frigate/installation
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.13.2@sha256:2906991ccad85035b176941f9dedfd35088ff710c39d45ef1baa9a49f2b16734
    privileged: true
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    volumes:
      - frigate-config:/config
      - frigate-media:/media/frigate
    tmpfs:
      - /tmp/cache
    shm_size: 2048M
    environment:
      FRIGATE_RTSP_PASSWORD: "balena"
      CONFIG_FILE: "/config/config.yml"
    labels:
      io.balena.features.kernel-modules: 1
    devices:
      - /dev/dri:/dev/dri

  # https://hub.docker.com/r/mrlt8/wyze-bridge/tags
  wyze-bridge:
    image: mrlt8/wyze-bridge:2.10.1@sha256:59b10ddc729dcee10adced1ddd83e1dbe2e9ac2438b7e0cae53a8041ad330356
    ports:
      # - 1935:1935 # RTMP
      # - 8554:8554 # RTSP
      # - 8888:8888 # HLS
      # - 8889:8889 # WebRTC
      # - 8189:8189/udp # WebRTC/ICE
      - 5001:5000 # WEB-UI
    volumes:
      - wyze-tokens:/tokens

  # https://hub.docker.com/r/tailscale/tailscale
  # https://github.com/tailscale/tailscale/blob/main/cmd/containerboot/main.go
  # https://tailscale.com/kb/1282/docker
  # https://tailscale.com/kb/1278/tailscaled
  # https://tailscale.com/kb/1241/tailscale-up
  # https://tailscale.com/kb/1242/tailscale-serve
  # https://tailscale.com/kb/1311/tailscale-funnel
  tailscale:
    image: tailscale/tailscale:v1.70.0@sha256:19c66f261912cd19fa5362d36cf6f4770ad6f273b410f940a0eba39b376fe326
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_SOCKET: /var/run/tailscale/tailscaled.sock
      TS_USERSPACE: false
      TS_AUTH_ONCE: false
      TS_HOSTNAME: homeassistant
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    tmpfs:
      - /tmp
      - /run
    volumes:
      - tailscale:/var/lib/tailscale
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        modprobe tun || true
        modprobe wireguard || true
        mkdir -p /dev/net
        [ ! -c /dev/net/tun ] && mknod /dev/net/tun c 10 200
        /usr/local/bin/containerboot

  netdata:
    image: netdata/netdata:v1.46.2@sha256:ea5a256b29ec592e7a13103d1632bfea0ce58365732d04c8fd32c8d740d3b1fb
    privileged: true
    network_mode: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.sysfs: 1
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "991" # ls -nd /var/run/balena.sock | awk '{print $4}'

volumes:
  config: {}
  influxdb: {}
  grafana: {}
  mqtt: {}
  zigbee2mqtt: {}
  duplicati: {}
  frigate-config: {}
  frigate-media: {}
  wyze-tokens: {}
  tailscale: {}
  netdatalib: {}
  netdatacache: {}
  esphome: {}
