version: "2.1"

services:
  # https://hub.docker.com/r/homeassistant/home-assistant
  homeassistant:
    image: homeassistant/home-assistant:2024.2.5@sha256:02304f6c5cdb817185e3a6f6db50aad97cf7206027c2a45fbf72da2d00588f4c
    network_mode: host
    volumes:
      - config:/config
    labels:
      io.balena.features.dbus: "1"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
    privileged: true

  # https://hub.docker.com/_/eclipse-mosquitto
  mqtt:
    build: mqtt
    ports:
      - 1883:1883
    volumes:
      - mqtt:/mosquitto/data
    tmpfs:
      - /mosquitto/log

  # https://esphome.io/guides/getting_started_command_line.html#installation
  esphome:
    image: ghcr.io/esphome/esphome:2023.12.9@sha256:310919056ef06f35aa815efce8b2c7c160b6adc1bfb7285afccabc432de38d86
    volumes:
      - esphome:/config
    privileged: true
    network_mode: host

  # https://www.zigbee2mqtt.io/guide/getting-started/#installation
  zigbee2mqtt:
    build: zigbee2mqtt
    volumes:
      - zigbee2mqtt:/app/data
    ports:
      - 7000:7000
    privileged: true

  # https://hub.docker.com/r/codercom/code-server
  code-server:
    image: codercom/code-server:4.21.1@sha256:c9f78fb7e8ac5fdd3bea856142dd5c5dda0f5183131254516af74135dc97c773
    command:
      - --port=9000
      - --auth=none
      - --extensions-dir=/config/.vscode
      - --user-data-dir=/config/.vscode
      - /config
    working_dir: /config
    ports:
      - 9000:9000/tcp
    volumes:
      - config:/config
      - zigbee2mqtt:/config/zigbee2mqtt
      - esphome:/config/esphome
      - frigate-config:/config/frigate
    user: root

  # https://hub.docker.com/_/influxdb
  influxdb:
    image: influxdb:1.8.10@sha256:f5ae6817fdfb667d0002c89a45e12207279ca1cf651cfb5bfe9126e1d906a559
    volumes:
      - influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  # https://hub.docker.com/r/grafana/grafana
  grafana:
    image: grafana/grafana:10.3.3@sha256:8640e5038e83ca4554ed56b9d76375158bcd51580238c6f5d8adaf3f20dd5379
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000/tcp

  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: homeassistant

  duplicati:
    image: linuxserver/duplicati:v2.0.6.3-2.0.6.3_beta_2021-06-17-ls154@sha256:bcd89eb054ff1bce2c438d5eaab39120ab71580d44317c41a65a8e1fd91fbda5
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - "8200:8200/tcp"
    tmpfs:
      - /tmp
    volumes:
      - duplicati:/config
      - config:/volumes/config
      - influxdb:/volumes/influxdb
      - grafana:/volumes/grafana
      - zigbee2mqtt:/volumes/zigbee2mqtt
      - frigate-media:/volumes/frigate-media
      - tailscale:/volumes/tailscale
      - netdatalib:/volumes/netdatalib
      - esphome:/volumes/esphome

  # https://docs.frigate.video/frigate/installation
  frigate:
    image: ghcr.io/blakeblackshear/frigate:0.13.2@sha256:2906991ccad85035b176941f9dedfd35088ff710c39d45ef1baa9a49f2b16734
    privileged: true
    ports:
      - "5000:5000"
      - "1935:1935" # RTMP feeds
    volumes:
      - frigate-config:/config
      - frigate-media:/media/frigate
    tmpfs:
      - /tmp/cache
    shm_size: 2048M
    environment:
      FRIGATE_RTSP_PASSWORD: "balena"
      CONFIG_FILE: "/config/config.yml"
    labels:
      io.balena.features.kernel-modules: 1
    devices:
      - /dev/dri:/dev/dri

  # https://hub.docker.com/r/mrlt8/wyze-bridge/tags
  wyze-bridge:
    image: mrlt8/wyze-bridge:2.7.0@sha256:c63e5b86d67d5ac1d5858769c3b147a4dc822ce3cd8968b9df1abad4c7a054d9
    ports:
      # - 1935:1935 # RTMP
      # - 8554:8554 # RTSP
      # - 8888:8888 # HLS
      # - 8889:8889 # WebRTC
      # - 8189:8189/udp # WebRTC/ICE
      - 5001:5000 # WEB-UI
    volumes:
      - wyze-tokens:/tokens

  # https://hub.docker.com/r/tailscale/tailscale
  # https://github.com/tailscale/tailscale/blob/main/cmd/containerboot/main.go
  # https://tailscale.com/kb/1282/docker
  # https://tailscale.com/kb/1278/tailscaled
  # https://tailscale.com/kb/1241/tailscale-up
  # https://tailscale.com/kb/1242/tailscale-serve
  # https://tailscale.com/kb/1311/tailscale-funnel
  tailscale:
    image: tailscale/tailscale:v1.61.11@sha256:06e993635efcfa9574147ed223424cba562f7a5f0785e3b74381477414d57227
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_SOCKET: /var/run/tailscale/tailscaled.sock
      TS_USERSPACE: false
      TS_AUTH_ONCE: false
      TS_HOSTNAME: homeassistant
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    tmpfs:
      - /tmp
      - /run
    volumes:
      - tailscale:/var/lib/tailscale
    entrypoint:
      - /bin/sh
      - -c
    command:
      - |
        modprobe tun || true
        modprobe wireguard || true
        mkdir -p /dev/net
        [ ! -c /dev/net/tun ] && mknod /dev/net/tun c 10 200
        /usr/local/bin/containerboot

  netdata:
    image: netdata/netdata:v1.44.3@sha256:9e89531a5ee14383cd400e6feafbff37cacbf5c3c4f5792e100d8d10b1f0aa2d
    privileged: true
    network_mode: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.sysfs: 1
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "991" # ls -nd /var/run/balena.sock | awk '{print $4}'

volumes:
  config: {}
  influxdb: {}
  grafana: {}
  mqtt: {}
  zigbee2mqtt: {}
  duplicati: {}
  frigate-config: {}
  frigate-media: {}
  wyze-tokens: {}
  tailscale: {}
  netdatalib: {}
  netdatacache: {}
  esphome: {}
